eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    name: service-provider
  cloud:
    config:
      uri: http://config-server

server:
  port: ${PORT:0}