server:
  port: 8888

spring:
  profiles:
    active: native # using local file system or classpath
  cloud:
    config:
      name: config-server
      override-system-properties: false
      server:
        native:
          search-locations:
            - classpath:/config-repo/{application}/{label} #{application} is essential
            - classpath:/config-repo/{application}

  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
